name: Run cryptofuzz command

on:
  push:
    branches:
      - CLI

jobs:
  run-command:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run install script
      run: |
        chmod +x install.sh
        ./install.sh

    - name: Execute cryptofuzz command
      run: python cryptofuzz --generate --total 10

